---
- name: VM from Template
  hosts: localhost
#  connection: local
#  gather_facts: false

  roles:
    - azure

  tasks:
    - name: Hello World!
      shell: echo "Hi! Tower is working."

  pre_tasks:
    - name: Pre tasks_Hello World!
      shell: echo "Pre taskas - Hi! Tower is working."
